mandatory1/blogproject/blogapp/urls.py
from django.urls import path

from . import views

app_name = 'blogapp'

urlpatterns = [
    # leave string empty so index is at root
    path('', views.index, name='index'),
    path('details/<int:pk>', views.details, name='details'),
   ]

mandatory1/blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
    path('blog/', include('blogapp.urls', namespace='blogapp')),
    path('admin/', admin.site.urls),
]

mandatory1/blogproject/loginapp/urls.py
from django.urls import path

from . import views

app_name = 'loginapp'

urlpatterns = [
    # leave string empty so index is at root
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', views.password_reset, name='password_reset'),
   ]

mandatory1/blogproject/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogItem(models.Model):
    # point to a specific user, if user is deleted, delete in the database
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    post = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    
    # return string to admin panel, to see which user has added which item
    def __str__(self):
        return f"{self.pk}, {self.title}, by {self.user}"

mandatory1/blogproject/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User

mandatory1/blogproject/blogapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse

# import models 
from .models import *

# Create your views here.
# give the view function parameter 'request' -  django will send a request to the view
@login_required
def index(request):
# if we get a GET req we should show what we have in the db
# if we get a POST req we should save the item in the db
    if request.method == 'GET':
        # get list of blog items from db - objects.all() will give ALL items in db
        blog_items = BlogItem.objects.filter(user=request.user)
      
        context = {
            'blogs': blog_items
        }
        # use render import  - give the request
        return render(request, 'blogapp/index.html', context)
    
    if request.method == 'POST':
        blog_item = BlogItem()
        blog_item.title = request.POST['title']
        blog_item.post = request.POST['post']
        # blog_item.date = request.POST['date']
        blog_item.user = request.user
        blog_item.save()
        return HttpResponseRedirect(reverse ('blogapp:index'))
    
    # will return a bad requeest to the user - better than sending back a server fault error
    return HttpResponseBadRequest()

@login_required
# convention to call ID for primary key
def details(request, pk):
    # get todo item from database - testing if the user is the one from the request
    blog = get_object_or_404(BlogItem, pk=pk, user=request.user)
    # print(todo.user)
    
    # if a user has clicked on a item-link and goes to the details page
    if request.method == 'GET':
        context = {
            'blog': blog
        }
        # render the template
        return render(request,'blogapp/details.html', context)

    if request.method == 'POST':
        # the user is on details page and hits submit button, get a post request with changes
        blog.title = request.POST.get('title')
        blog.post = request.POST.get('post')
        blog.save()
        # return/redirect to index view
        return HttpResponseRedirect(reverse ('blogapp:index'))

    return HttpResponseBadRequest()

mandatory1/blogproject/loginapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
# from django.contrib.auth.decorators
from .utils import random_string

# from .models import *

# Create your views here.

def login(request):
    # now the context exists but it is empty by default
    context = {}

    if request.method == 'POST':
        # request.POST is a dictionary, you need a key to get the value
        user = authenticate(request, 
            username=request.POST['user'], 
            password=request.POST['password'])
        # check if user is real
        if user:
            # if user is in the system, redirect them
            dj_login(request, user)
            #context = {'user':request.POST['user']} - useless, not passing the context to the return
            return HttpResponseRedirect(reverse ('blogapp:index'))
        else:
            # send error message
            # context = {'error':'Username or password is wrong.'}
            context['error'] = "Username or password is wrong."

    # don't receive a post request, render template as default
    # request and url are required arguments, context is not require
    return render(request, 'loginapp/login.html', context)

def logout(request):
    dj_logout(request)
    # redirect user if they logout
    return HttpResponseRedirect(reverse ('loginapp:login'))



def signup(request):
    if User.is_authenticated:
        dj_logout(request)

    if request.method == 'POST':
        # fill it out with what i need on the way
        context = {}
        # use if not - can easily go out, if it is wrong
        if not request.POST['password'] == request.POST['confirmPassword']:
            #if they dont match, put an error message in the context
            context['error'] = "Passwords do not match."
            # if it is wrong, render the template and send the context
            return render(request, 'loginapp/signup.html', context)
        #check if the list of users is empty or not - use len
        if len(User.objects.filter(username = request.POST['user'])) > 0:
            # if the user already exists, send new error message
            context['error'] = 'Username already exists'
            return render(request, 'loginapp/signup.html', context)

        # create user
        user = User.objects.create_user(request.POST['user'],password=request.POST['password'])
        user.save()
        dj_login(request, user)
        return HttpResponseRedirect(reverse ('blogapp:index'))
        

    # if it is not a post (then it is a get) it should just show the signup form
    return render(request, 'loginapp/signup.html')


def password_reset(request):
    context = {}
    # user should provide the username
    if request.method == 'POST':
    # generate a random string for password and show it in the console 

        # filter can return many things, it is a list - test if the list is empty
        users = User.objects.filter(username=request.POST['user'])
        # if user exists, grab the user
        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'*********** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))

        # if the list is empty, send back an error
        else:
            context['error'] = "No such username"

    return render(request, 'loginapp/password_reset.html', context)

mandatory1/blogproject/blogapp/templates/blogapp/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
    body{
       padding: 2%;
    }

    .form-control{
        width: 600px;
    }
    button{
        background-color: #007bff!important;
        color: white!important;
    }
    </style>
</head>
<body>
    <h1>Edit blogpost</h1>
        <p>User logged in: {{ blog.user }}</p>
        
    <!-- dot as action sends it back to ouselves?? -->
    <form action="{% url 'blogapp:details' blog.pk %}" method="POST">
        <!-- prevent js injection and cross script attacks with csrf_token-->
        {% csrf_token %}
            <label for="title">Title</label>
            <!-- todo.title comes from the contect in views.py, whatever is in the dictionary is available for the template  -->
            <input id="title" name="title" type="text" placeholder="Title" value="{{ blog.title }}" class="form-control"><br>
            <label for="post">Post</label><br>
            <textarea id="post" name="post" class="form-control">{{ blog.post }}</textarea><br>
            <button class="form-control">Submit</button>
    </form>

</body>
</html>

mandatory1/blogproject/blogapp/templates/blogapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog app</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
    body{
       padding: 2%;
    }

    #createPost{
        width: 600px;
        /* border: 2px solid red; */
    }
    .blogSection{
        width: 600px;
        padding: 20px;
        box-shadow: 5px 10px 18px #888888:
    }
    button{
        background-color: #007bff!important;
        color: white!important;
    }
    </style>
</head>
<body>
    <h1>Blog App</h1>
        <p>{{ blog.user }}</p>
    <hr>
    <a href="{% url 'loginapp:logout' %}">LOGOUT</a>
    <hr>
    <!-- reference to the context -> todos in views.py -->
        <!-- for loop for todos, and every item will be called todo -->
        {% for blog in blogs %}
            <div class="blogSection">
                <div id="blogDate">Posted: {{ blog.date }}</div>
                <!-- click on url should go to details page and pass primary key along with it -->
                <div id="blogTitle"><h4>{{ blog.title }}</h4></div>
                <div id="blogPost">{{ blog.post }}</div>
                <a href="{% url 'blogapp:details' blog.pk %}">EDIT</a>
                <hr>
            </div>
        {% endfor %}
    <hr>

    <form action="." method="POST">
        <div id="createPost">
            <div class="form-group">
                {% csrf_token %}
                <label for="title">Blog title</label><br>
                <input id="title" name="title" type="text" placeholder="Title" class="form-control"><br>
                <label for="post">Blog post</label><br>
                <textarea id="post" name="post" class="form-control">{{ blog.post }}</textarea><br>
                <button class="form-control">Submit</button>
            </div>
        </div>
    </form>
    
</body>
</html>

mandatory1/blogproject/loginapp/templates/loginapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
    body{
       padding: 2%;
    }

    .form-control{
        width: 400px;
    }
    button{
        background-color: #007bff!important;
        color: white!important;
    }
    </style>
</head>
<body>
    <h1>Login</h1>

    <form action="." method="POST">
        {% comment %} makes sure the token is resubmitted when something is posted, to prevent cross site scripting {% endcomment %}
        {% csrf_token %}
        <label for="user">Username</label>
        <input type="text" name="user" id="user" placehoder="Username" class="form-control">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" placehoder="Password" class="form-control">
        <input type="submit" value="Submit" class="form-control">
    </form>

    
    {% comment %} error message if username/password is wrong, get it from views  {% endcomment %}
    {% if error %} 
        <p class="error"> {{ error }} </p> 
        <p><a href="{% url 'loginapp:password_reset' %}">Reset password</a></p>
    {% endif %}
    
    <a href="{% url 'loginapp:signup' %}">Sign up here</a>
</body>
</html>

mandatory1/blogproject/loginapp/templates/loginapp/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password reset</title>
</head>
<body>
    <h1>Password reset</h1>

    <form action="{% url 'loginapp:password_reset' %}" method="POST">
        {% comment %} makes sure the token is resubmitted when something is posted, to prevent cross site scripting {% endcomment %}
        {% csrf_token %}
        <label for="user">Username</label>
        <input type="text" name="user" id="user" placehoder="Username">
        <input type="submit" value="Submit">
    </form>

    
    {% comment %} error message if username/password is wrong, get it from views  {% endcomment %}
    {% if error %} 
        <p class="error"> {{ error }} </p> 
    {% endif %}
    
</body>
</html>

mandatory1/blogproject/loginapp/templates/loginapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
    body{
       padding: 2%;
    }

    .form-control{
        width: 400px;
    }
    button{
        background-color: #007bff!important;
        color: white!important;
    }
    </style>
</head>
<body>
    <h1>Signup</h1>

    <form action="{% url 'loginapp:signup' %}" method="POST">
        {% comment %} makes sure the token is resubmitted when something is posted, to prevent cross site scripting {% endcomment %}
        {% csrf_token %}
        <label for="user">Username</label>
        <input type="text" name="user" id="user" placehoder="Username" class="form-control">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" placehoder="Password" class="form-control">
        <label for="confirmPassword">Confirm password</label>
        <input type="password" name="confirmPassword" id="confirmPassword" placehoder="confirmPassword" class="form-control">
        <!-- <input class="button" type="submit" value="Submit" class="form-control"> -->
        <button class="form-control">Submit</button>
    </form>

    {% comment %} error message if username/password is wrong, get it from views  {% endcomment %}
    {% comment %} {% if error %} <p class="error"> {{ error }} </p> {% endif %} {% endcomment %}

</body>
</html>